# api redirect.
[[redirects]]
  from = "/api/*"
  to = "https://movabackend.herokuapp.com/api/:splat"
  status = 200
# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200